"""PostgreSQL-klargjoring, fase 2: kurs/schema_postgres.sql skal SPEILE kurs/schema.sql.

Sammenligner tabell for tabell: kolonner (navn og rekkefolge), type (med fast oversettelse), NOT NULL, standardverdi,
UNIQUE, primaernokkel/identitet, fremmednokler (inkl. ON DELETE CASCADE), CHECK, tabellbegrensninger og unike indekser.
Endres det ene skjemaet uten det andre, feiler testen. I tillegg kontrolleres selve parseren mot SQLite sin egen
beskrivelse av databasen (PRAGMA), saa en feil i parseren ikke kan skjule avvik.
"""
import re
import sqlite3
from pathlib import Path

import pytest

from kurs import db

KURS = Path(__file__).resolve().parent.parent / "kurs"
SQLITE_SKJEMA = (KURS / "schema.sql").read_text(encoding="utf-8")
PG_SKJEMA = (KURS / "schema_postgres.sql").read_text(encoding="utf-8")

TYPE_SQLITE_TIL_PG = {"INTEGER": "BIGINT", "REAL": "DOUBLE PRECISION", "TEXT": "TEXT"}
NAA_SQLITE = "(datetime('now'))"
NAA_PG = "(to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))"


def _del_paa_toppnivaa(tekst: str) -> list[str]:
    """Deler paa komma som ikke staar inne i parenteser (CHECK (...), COALESCE(...) osv.)."""
    deler, dybde, buf = [], 0, []
    for tegn in tekst:
        if tegn == "(":
            dybde += 1
        elif tegn == ")":
            dybde -= 1
        if tegn == "," and dybde == 0:
            deler.append("".join(buf))
            buf = []
        else:
            buf.append(tegn)
    deler.append("".join(buf))
    return [" ".join(d.split()) for d in deler if d.strip()]


def _balansert(tekst: str, start: int) -> str:
    """Innholdet i parentesen som begynner paa `start` (inkludert parentesene)."""
    dybde = 0
    for i in range(start, len(tekst)):
        dybde += {"(": 1, ")": -1}.get(tekst[i], 0)
        if dybde == 0:
            return tekst[start:i + 1]
    raise ValueError("ubalansert parentes")


def _kolonne(definisjon: str) -> dict:
    navn, resten = definisjon.split(" ", 1)
    type_ = "DOUBLE PRECISION" if resten.startswith("DOUBLE PRECISION") else resten.split(" ")[0]
    default = None
    m = re.search(r"\bDEFAULT (\(|'|-?\d)", resten)
    if m:
        s = m.start(1)
        default = (_balansert(resten, s) if resten[s] == "(" else
                   resten[s:resten.index("'", s + 1) + 1] if resten[s] == "'" else re.match(r"-?\d+", resten[s:]).group())
    check = None
    if " CHECK " in f" {resten} ":
        check = _balansert(resten, resten.index("CHECK") + len("CHECK "))
    ref = re.search(r"REFERENCES (\w+)\((\w+)\)( ON DELETE CASCADE)?", resten)
    return {
        "navn": navn, "type": type_,
        "nocase": "COLLATE NOCASE" in resten or type_ == "CITEXT",
        "not_null": "NOT NULL" in resten or "PRIMARY KEY" in resten,
        "pk": "PRIMARY KEY" in resten, "identitet": "GENERATED BY DEFAULT AS IDENTITY" in resten,
        "unique": bool(re.search(r"\bUNIQUE\b", resten)),
        "default": default, "check": check,
        "ref": (ref.group(1), ref.group(2), bool(ref.group(3))) if ref else None,
    }


def _parse(skjema: str) -> tuple[dict, dict]:
    uten_kommentarer = re.sub(r"--[^\n]*", "", skjema)
    tabeller = {}
    for m in re.finditer(r"CREATE TABLE IF NOT EXISTS (\w+) \(", uten_kommentarer):
        kropp = _balansert(uten_kommentarer, m.end() - 1)[1:-1]
        kolonner, begrensninger = [], []
        for d in _del_paa_toppnivaa(kropp):
            (begrensninger if re.match(r"(PRIMARY KEY|UNIQUE|CHECK|FOREIGN KEY|CONSTRAINT)\b", d) else kolonner).append(d)
        tabeller[m.group(1)] = {"kolonner": [_kolonne(k) for k in kolonner], "begrensninger": begrensninger}
    indekser = {m.group(1): (m.group(2), " ".join(m.group(3).split()))
                for m in re.finditer(r"CREATE UNIQUE INDEX IF NOT EXISTS (\w+) ON (\w+) \((.*?)\);", uten_kommentarer)}
    return tabeller, indekser


SQLITE_TAB, SQLITE_IDX = _parse(SQLITE_SKJEMA)
PG_TAB, PG_IDX = _parse(PG_SKJEMA)


# ============================ parseren er riktig (kontrollert mot SQLite selv) ============================

def test_parseren_ser_det_samme_som_sqlite(tmp_path):
    c = db.koble(tmp_path / "s.db")
    db.init(c)
    ekte = {r["name"] for r in c.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    assert set(SQLITE_TAB) == ekte
    for tabell, info in SQLITE_TAB.items():
        pragma = list(c.execute(f"PRAGMA table_info({tabell})"))
        assert [k["navn"] for k in info["kolonner"]] == [r["name"] for r in pragma], tabell
        for k, r in zip(info["kolonner"], pragma):
            default = k["default"]
            if default and default.startswith("(") and _balansert(default, 0) == default:
                default = default[1:-1]                      # PRAGMA viser uttrykk uten ytre parentes
            assert k["type"] == r["type"] and default == r["dflt_value"], (tabell, k["navn"])
            assert k["not_null"] == bool(r["notnull"] or r["pk"]), (tabell, k["navn"])
    c.close()


def test_parseren_fant_alle_tabeller_og_indekser():
    assert len(SQLITE_TAB) == 23 and set(SQLITE_IDX) == {"faktura_unik", "faktura_forsok_unik"}


# ============================ speiling ============================

def test_samme_tabeller_og_indekser():
    assert set(PG_TAB) == set(SQLITE_TAB)
    assert PG_IDX == SQLITE_IDX


@pytest.mark.parametrize("tabell", sorted(SQLITE_TAB))
def test_samme_kolonner_i_samme_rekkefolge(tabell):
    assert [k["navn"] for k in PG_TAB[tabell]["kolonner"]] == [k["navn"] for k in SQLITE_TAB[tabell]["kolonner"]]


@pytest.mark.parametrize("tabell", sorted(SQLITE_TAB))
def test_kolonnene_er_likeverdige(tabell):
    for s, p in zip(SQLITE_TAB[tabell]["kolonner"], PG_TAB[tabell]["kolonner"]):
        hvor = f"{tabell}.{s['navn']}"
        forventet_type = "CITEXT" if s["nocase"] else TYPE_SQLITE_TIL_PG[s["type"]]
        assert p["type"] == forventet_type, hvor
        assert p["nocase"] == s["nocase"], hvor
        assert (p["not_null"], p["pk"], p["unique"], p["ref"], p["check"]) == (
            s["not_null"], s["pk"], s["unique"], s["ref"], s["check"]), hvor
        assert p["default"] == (NAA_PG if s["default"] == NAA_SQLITE else s["default"]), hvor
        # SQLite: «id INTEGER PRIMARY KEY» faar automatisk id. PostgreSQL: identitetskolonne - og KUN der.
        assert p["identitet"] == (s["navn"] == "id" and s["pk"] and s["type"] == "INTEGER"), hvor


@pytest.mark.parametrize("tabell", sorted(SQLITE_TAB))
def test_samme_tabellbegrensninger(tabell):
    assert PG_TAB[tabell]["begrensninger"] == SQLITE_TAB[tabell]["begrensninger"]


def test_nocase_kolonnene_er_citext():
    nocase = {(t, k["navn"]) for t, i in SQLITE_TAB.items() for k in i["kolonner"] if k["nocase"]}
    assert nocase == {("deltaker", "epost"), ("admin_bruker", "brukernavn"), ("utsending_logg", "mottaker")}
    assert "CREATE EXTENSION IF NOT EXISTS citext;" in PG_SKJEMA


def test_postgres_skjemaet_har_ingen_sqlite_dialekt():
    uten_kommentarer = re.sub(r"--[^\n]*", "", PG_SKJEMA)
    for m in (r"PRAGMA", r"datetime\(", r"COLLATE NOCASE", r"\bINTEGER\b", r"\bREAL\b", r"AUTOINCREMENT"):
        assert not re.search(m, uten_kommentarer), m


def test_refererte_tabeller_er_definert_foer_de_brukes_i_postgres():
    rekkefolge = list(PG_TAB)
    for tabell, info in PG_TAB.items():
        for k in info["kolonner"]:
            if k["ref"] and k["ref"][0] != tabell:
                assert rekkefolge.index(k["ref"][0]) < rekkefolge.index(tabell), (tabell, k["navn"], k["ref"][0])


def test_migreringskolonner_finnes_i_begge_skjemaer():
    """Kolonner som db._migrer legger til i gamle SQLite-databaser, maa finnes i begge skjemaene."""
    kode = (KURS / "db.py").read_text(encoding="utf-8")
    for tabell, kolonne in re.findall(r'har_kolonne\(con, "(\w+)", "(\w+)"\)', kode):
        for skjema in (SQLITE_TAB, PG_TAB):
            assert kolonne in [k["navn"] for k in skjema[tabell]["kolonner"]], (tabell, kolonne)
