-- IPR kursautomasjon – datamodell for PostgreSQL (brukes naar DATABASE_URL er satt).
-- SPEILER kurs/schema.sql (SQLite): samme tabeller, kolonner (samme rekkefolge), NOT NULL, standardverdier, CHECK,
-- UNIQUE, fremmednokler og indekser. tests/test_skjema_speiling.py feiler hvis de to glir fra hverandre.
-- Kjoeres av `python -m kurs.migrer` (db.init) - idempotent (IF NOT EXISTS), aldri av gunicorn.
--
-- Oversettelser fra SQLite:
--   * INTEGER (64-bit i SQLite)        -> BIGINT
--   * id INTEGER PRIMARY KEY           -> id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   * REAL                             -> DOUBLE PRECISION
--   * TEXT ... COLLATE NOCASE          -> CITEXT (krever utvidelsen citext)
--   * DEFAULT (datetime('now'))        -> samme tekstformat og tidssone: 'YYYY-MM-DD HH:MM:SS' i UTC
--   * PRAGMA foreign_keys              -> ikke noedvendig (PostgreSQL haandhever alltid fremmednokler)
--   * admin_bruker er flyttet foerst, fordi PostgreSQL krever at en tabell finnes foer den kan refereres til.
-- Tidsstempler og datoer lagres bevisst som TEXT (som i SQLite), saa all eksisterende kode og alle sammenligninger
-- virker uendret.

CREATE EXTENSION IF NOT EXISTS citext;

-- Ansatte som kan logge inn i administrasjonen. Passord lagres kun som hash (aldri klartekst).
CREATE TABLE IF NOT EXISTS admin_bruker (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brukernavn      CITEXT UNIQUE NOT NULL,
    navn            TEXT NOT NULL,
    passord_hash    TEXT NOT NULL,
    aktiv           BIGINT NOT NULL DEFAULT 1,
    rolle           TEXT NOT NULL DEFAULT 'kursadmin' CHECK (rolle IN ('system','kursadmin','lese')),
    entra_oid       TEXT UNIQUE,
    epost           TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS kurs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kursnr          BIGINT UNIQUE,
    kode            TEXT UNIQUE NOT NULL,
    navn            TEXT NOT NULL,
    type            TEXT NOT NULL DEFAULT 'digital' CHECK (type IN ('digital','fysisk','hybrid')),
    status          TEXT NOT NULL DEFAULT 'aapen' CHECK (status IN ('utkast','aapen','full','aktiv','avsluttet','avlyst')),
    sted            TEXT,
    start_kl        TEXT NOT NULL DEFAULT '09:00',
    slutt_kl        TEXT NOT NULL DEFAULT '16:00',
    timer_pr_dag    DOUBLE PRECISION NOT NULL DEFAULT 6,
    kapasitet       BIGINT,
    pris_nok        BIGINT NOT NULL DEFAULT 0,
    fakturering     TEXT NOT NULL DEFAULT 'person' CHECK (fakturering IN ('person','organisasjon','ingen')),
    betaling        TEXT NOT NULL DEFAULT 'samlet' CHECK (betaling IN ('samlet','per_samling','deltaker_velger')),
    faktura_dager_for BIGINT NOT NULL DEFAULT 14,
    visma_artikkel  TEXT,
    spesialistlop   TEXT,
    kursholder_epost TEXT,
    zoom_url        TEXT,
    zoom_id         TEXT,
    zoom_pw         TEXT,
    sharepoint_mappe TEXT,
    notat           TEXT,
    ansvarlig_admin_id BIGINT REFERENCES admin_bruker(id),
    paameldingsfrist TEXT,
    paamelding_intro TEXT,
    paamelding_knappetekst TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS kursdag (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id) ON DELETE CASCADE,
    dato            TEXT NOT NULL,
    start_kl        TEXT,
    slutt_kl        TEXT,
    innsjekk_token  TEXT UNIQUE NOT NULL,
    innsjekk_kode   TEXT NOT NULL,
    UNIQUE (kurs_id, dato)
);

CREATE TABLE IF NOT EXISTS deltaker (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epost           CITEXT UNIQUE NOT NULL,
    navn            TEXT NOT NULL,
    telefon         TEXT,
    arbeidssted     TEXT,
    yrkestittel     TEXT,
    hpr_nr          TEXT,
    visma_kunde_id  TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS paamelding (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id),
    deltaker_id     BIGINT NOT NULL REFERENCES deltaker(id),
    status          TEXT NOT NULL DEFAULT 'bekreftet' CHECK (status IN ('bekreftet','venteliste','avmeldt')),
    betaler         TEXT NOT NULL DEFAULT 'person' CHECK (betaler IN ('person','organisasjon')),
    betaling        TEXT NOT NULL DEFAULT 'samlet' CHECK (betaling IN ('samlet','per_samling')),
    org_navn        TEXT,
    org_nr          TEXT,
    faktura_epost   TEXT,
    faktura_adresse TEXT,
    faktura_postnr  TEXT,
    faktura_sted    TEXT,
    faktura_ref     TEXT,
    ehf             BIGINT NOT NULL DEFAULT 0,
    rabattkode      TEXT,
    samtykke_ts     TEXT,
    kilde           TEXT NOT NULL DEFAULT 'skjema',
    sveiper_kjort   BIGINT NOT NULL DEFAULT 0,
    sveiper_utsatt  BIGINT NOT NULL DEFAULT 0,
    faktura_onskes_na BIGINT NOT NULL DEFAULT 0,
    faktura_tidligst_dato TEXT,
    faktura_kommentar TEXT,
    intern_kommentar  TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    oppdatert       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    avslatt_ts      TEXT,
    UNIQUE (kurs_id, deltaker_id)
);

-- Sensitive opplysninger holdes adskilt og slettes N dager etter kursslutt
CREATE TABLE IF NOT EXISTS sensitivt (
    paamelding_id   BIGINT PRIMARY KEY REFERENCES paamelding(id) ON DELETE CASCADE,
    allergier       TEXT,
    tilrettelegging TEXT
);

CREATE TABLE IF NOT EXISTS faktura (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paamelding_id   BIGINT NOT NULL REFERENCES paamelding(id),
    kursdag_id      BIGINT REFERENCES kursdag(id),
    visma_id        TEXT,
    faktura_nr      TEXT,
    belop_nok       BIGINT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'opprettet' CHECK (status IN ('opprettet','sendt','betalt','kreditert','feil')),
    feilmelding     TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

-- Aldri dobbeltfakturering: én samlet faktura, eller én per samling.
CREATE UNIQUE INDEX IF NOT EXISTS faktura_unik ON faktura (paamelding_id, COALESCE(kursdag_id, 0));

-- Forsoket paa aa lage en faktura i Visma (se kommentaren i schema.sql).
CREATE TABLE IF NOT EXISTS faktura_forsok (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paamelding_id   BIGINT NOT NULL REFERENCES paamelding(id),
    kursdag_id      BIGINT REFERENCES kursdag(id),
    status          TEXT NOT NULL CHECK (status IN ('reservert','feilet','ukjent')),
    feilmelding     TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE UNIQUE INDEX IF NOT EXISTS faktura_forsok_unik ON faktura_forsok (paamelding_id, COALESCE(kursdag_id, 0));

CREATE TABLE IF NOT EXISTS oppmote (
    paamelding_id   BIGINT NOT NULL REFERENCES paamelding(id),
    kursdag_id      BIGINT NOT NULL REFERENCES kursdag(id),
    kilde           TEXT NOT NULL CHECK (kilde IN ('qr','kode','zoom','manuell')),
    minutter        BIGINT,
    ts              TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    PRIMARY KEY (paamelding_id, kursdag_id)
);

CREATE TABLE IF NOT EXISTS dokument (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT REFERENCES kurs(id),
    deltaker_id     BIGINT REFERENCES deltaker(id),
    type            TEXT NOT NULL CHECK (type IN ('presentasjon','kontrakt','kursbevis','veiledning','annet')),
    tittel          TEXT NOT NULL,
    url             TEXT NOT NULL,
    publisert       BIGINT NOT NULL DEFAULT 1,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS materiell_krav (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id),
    ansvarlig_navn  TEXT NOT NULL,
    ansvarlig_epost TEXT NOT NULL,
    beskrivelse     TEXT NOT NULL DEFAULT 'Kurspresentasjon',
    frist           TEXT NOT NULL,
    levert_ts       TEXT
);

-- Dedup for ALL utsending (se kommentaren i schema.sql). mottaker er CITEXT: unikheten og oppslagene ignorerer store/
-- smaa bokstaver, akkurat som COLLATE NOCASE i SQLite - ellers kunne samme e-post blitt sendt to ganger.
CREATE TABLE IF NOT EXISTS utsending_logg (
    nokkel          TEXT NOT NULL,
    mottaker        CITEXT NOT NULL,
    type            TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'sendt' CHECK (status IN ('reservert','sendt','feilet','ukjent')),
    sendt_ts        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    UNIQUE (nokkel, mottaker, type)
);

CREATE TABLE IF NOT EXISTS admin_utsending (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nokkel          TEXT UNIQUE NOT NULL,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id),
    emne            TEXT NOT NULL,
    tekst           TEXT NOT NULL,
    sendt_av_admin_id BIGINT REFERENCES admin_bruker(id),
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS admin_utsending_mottaker (
    utsending_id    BIGINT NOT NULL REFERENCES admin_utsending(id) ON DELETE CASCADE,
    paamelding_id   BIGINT NOT NULL REFERENCES paamelding(id),
    PRIMARY KEY (utsending_id, paamelding_id)
);

CREATE TABLE IF NOT EXISTS firmapaamelding (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id),
    innsendingsnokkel TEXT UNIQUE NOT NULL,
    kvittering_token  TEXT UNIQUE NOT NULL,
    kontakt_navn    TEXT NOT NULL,
    kontakt_epost   TEXT NOT NULL,
    kontakt_telefon TEXT,
    firmanavn       TEXT NOT NULL,
    org_nr          TEXT,
    faktura_ref     TEXT,
    faktura_adresse TEXT,
    faktura_postnr  TEXT,
    faktura_sted    TEXT,
    ehf             BIGINT NOT NULL DEFAULT 0,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS firmapaamelding_rad (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firmapaamelding_id  BIGINT NOT NULL REFERENCES firmapaamelding(id) ON DELETE CASCADE,
    navn                TEXT NOT NULL,
    epost               TEXT NOT NULL,
    paamelding_id       BIGINT REFERENCES paamelding(id),
    feilmelding         TEXT
);

CREATE TABLE IF NOT EXISTS innlogging_token (
    token           TEXT PRIMARY KEY,
    deltaker_id     BIGINT NOT NULL REFERENCES deltaker(id),
    utloper         TEXT NOT NULL,
    brukt           BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS import_forhaandsvisning (
    token           TEXT PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id),
    admin_id        BIGINT NOT NULL REFERENCES admin_bruker(id),
    rader_json      TEXT NOT NULL,
    resultater_json TEXT NOT NULL,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    utloper         TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS hendelse (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts              TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    aktor           TEXT NOT NULL,
    handling        TEXT NOT NULL,
    detaljer        TEXT
);

CREATE TABLE IF NOT EXISTS kunnskap (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kategori        TEXT NOT NULL,
    sporsmal        TEXT NOT NULL,
    svar            TEXT NOT NULL,
    kurs_id         BIGINT REFERENCES kurs(id),
    gyldig_til      TEXT,
    godkjent        BIGINT NOT NULL DEFAULT 0,
    oppdatert       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    oppdatert_av    TEXT
);

CREATE TABLE IF NOT EXISTS henvendelse (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts              TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    deltaker_id     BIGINT REFERENCES deltaker(id),
    epost           TEXT,
    sporsmal        TEXT NOT NULL,
    status          TEXT NOT NULL CHECK (status IN ('besvart','til_adm','lukket')),
    kilder          TEXT,
    grunn           TEXT
);

CREATE TABLE IF NOT EXISTS mal_tekst (
    mal             TEXT NOT NULL,
    felt            TEXT NOT NULL,
    tekst           TEXT NOT NULL,
    oppdatert       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    oppdatert_av    TEXT,
    PRIMARY KEY (mal, felt)
);

CREATE TABLE IF NOT EXISTS teller (
    navn            TEXT PRIMARY KEY,
    verdi           BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS schema_versjon (
    versjon         BIGINT PRIMARY KEY,
    navn            TEXT NOT NULL,
    kjort           TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS kurs_skjemafelt (
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id) ON DELETE CASCADE,
    felt            TEXT NOT NULL,
    synlig          BIGINT CHECK (synlig IS NULL OR synlig IN (0,1)),
    obligatorisk    BIGINT CHECK (obligatorisk IS NULL OR obligatorisk IN (0,1)),
    rekkefolge      BIGINT,
    label           TEXT,
    hjelpetekst     TEXT,
    oppdatert       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    oppdatert_av    TEXT,
    PRIMARY KEY (kurs_id, felt)
);

CREATE TABLE IF NOT EXISTS planlagt_aktivitet (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            TEXT NOT NULL DEFAULT 'plan' CHECK (type IN ('plan','notat')),
    tittel          TEXT NOT NULL,
    fra_dato        TEXT NOT NULL,
    til_dato        TEXT NOT NULL,
    sted            TEXT,
    notat           TEXT,
    opprettet_av    TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    CHECK (til_dato >= fra_dato)
);

CREATE TABLE IF NOT EXISTS dokument_innhold (
    dokument_id     BIGINT PRIMARY KEY REFERENCES dokument(id) ON DELETE CASCADE,
    mimetype        TEXT NOT NULL DEFAULT 'text/html',
    innhold         TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS integrasjon_token (
    navn            TEXT PRIMARY KEY,
    verdi           TEXT NOT NULL,
    oppdatert       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
