-- IPR kursautomasjon – datamodell for PostgreSQL (brukes naar DATABASE_URL er satt).
-- SPEILER kurs/schema.sql (SQLite): samme tabeller, kolonner (samme rekkefolge), NOT NULL, standardverdier, CHECK,
-- UNIQUE, fremmednokler og indekser. tests/test_skjema_speiling.py feiler hvis de to glir fra hverandre.
-- Kjoeres av `python -m kurs.migrer` (db.init) - idempotent (IF NOT EXISTS), aldri av gunicorn.
--
-- Oversettelser fra SQLite:
--   * INTEGER (64-bit i SQLite)        -> BIGINT
--   * id INTEGER PRIMARY KEY           -> id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   * REAL                             -> DOUBLE PRECISION
--   * TEXT ... COLLATE NOCASE          -> CITEXT (krever utvidelsen citext)
--   * DEFAULT (datetime('now'))        -> samme tekstformat og tidssone: 'YYYY-MM-DD HH:MM:SS' i UTC
--   * PRAGMA foreign_keys              -> ikke noedvendig (PostgreSQL haandhever alltid fremmednokler)
--   * admin_bruker er flyttet foerst, fordi PostgreSQL krever at en tabell finnes foer den kan refereres til. Av
--     samme grunn staar signatur (som admin_bruker og kurs viser til) aller foerst.
-- Tidsstempler og datoer lagres bevisst som TEXT (som i SQLite), saa all eksisterende kode og alle sammenligninger
-- virker uendret.

CREATE EXTENSION IF NOT EXISTS citext;

-- Signaturbiblioteket: se schema.sql.
CREATE TABLE IF NOT EXISTS signatur (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    navn            TEXT NOT NULL,
    innhold         TEXT NOT NULL DEFAULT '',
    standard        BIGINT NOT NULL DEFAULT 0,
    versjon         BIGINT NOT NULL DEFAULT 1,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    opprettet_av    TEXT,
    endret          TEXT,
    endret_av       TEXT
);

CREATE TABLE IF NOT EXISTS signatur_bilde (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filnavn         TEXT NOT NULL,
    mimetype        TEXT NOT NULL,
    bredde          BIGINT NOT NULL,
    hoyde           BIGINT NOT NULL,
    storrelse       BIGINT NOT NULL,
    sha256          TEXT NOT NULL,
    alt             TEXT NOT NULL,
    innhold         TEXT NOT NULL,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    opprettet_av    TEXT
);

-- Ansatte som kan logge inn i administrasjonen. Passord lagres kun som hash (aldri klartekst).
CREATE TABLE IF NOT EXISTS admin_bruker (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brukernavn      CITEXT UNIQUE NOT NULL,
    navn            TEXT NOT NULL,
    passord_hash    TEXT NOT NULL,
    aktiv           BIGINT NOT NULL DEFAULT 1,
    rolle           TEXT NOT NULL DEFAULT 'kursadmin' CHECK (rolle IN ('system','kursadmin','lese')),
    entra_oid       TEXT UNIQUE,
    epost           TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    hovedsignatur_id BIGINT REFERENCES signatur(id)
);

CREATE TABLE IF NOT EXISTS kurs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kursnr          BIGINT UNIQUE,
    kode            TEXT UNIQUE NOT NULL,
    navn            TEXT NOT NULL,
    type            TEXT NOT NULL DEFAULT 'digital' CHECK (type IN ('digital','fysisk','hybrid')),
    status          TEXT NOT NULL DEFAULT 'aapen' CHECK (status IN ('utkast','aapen','full','aktiv','avsluttet','avlyst')),
    sted            TEXT,
    start_kl        TEXT NOT NULL DEFAULT '09:00',
    slutt_kl        TEXT NOT NULL DEFAULT '16:00',
    timer_pr_dag    DOUBLE PRECISION NOT NULL DEFAULT 6,
    kapasitet       BIGINT,
    pris_nok        BIGINT NOT NULL DEFAULT 0,
    fakturering     TEXT NOT NULL DEFAULT 'person' CHECK (fakturering IN ('person','organisasjon','ingen')),
    betaling        TEXT NOT NULL DEFAULT 'samlet' CHECK (betaling IN ('samlet','per_samling','deltaker_velger')),
    faktura_dager_for BIGINT NOT NULL DEFAULT 14,
    visma_artikkel  TEXT,
    spesialistlop   TEXT,
    kursholder_epost TEXT,
    zoom_url        TEXT,
    zoom_id         TEXT,
    zoom_pw         TEXT,
    sharepoint_mappe TEXT,
    notat           TEXT,
    ansvarlig_admin_id BIGINT REFERENCES admin_bruker(id),
    paameldingsfrist TEXT,
    paamelding_intro TEXT,
    paamelding_knappetekst TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    paameldingsfrist_manuell BIGINT NOT NULL DEFAULT 0,
    signatur_id     BIGINT REFERENCES signatur(id),
    signatur_html   TEXT
);

CREATE TABLE IF NOT EXISTS samling (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id) ON DELETE CASCADE,
    navn            TEXT,
    start_kl        TEXT NOT NULL,
    slutt_kl        TEXT NOT NULL,
    timer_pr_dag    DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS kursdag (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id) ON DELETE CASCADE,
    dato            TEXT NOT NULL,
    start_kl        TEXT,
    slutt_kl        TEXT,
    innsjekk_token  TEXT UNIQUE NOT NULL,
    innsjekk_kode   TEXT NOT NULL,
    samling_id      BIGINT REFERENCES samling(id),
    merknad         TEXT,
    timer           DOUBLE PRECISION,
    UNIQUE (kurs_id, dato)
);

-- Deltakerens PRIVATE adresse (adresse, postnr, poststed - migrering 14): påkrevd for alle deltakere i alle veier inn. En
-- personopplysning (ikke sensitiv etter art. 9): aldri i logger, e-post eller eksport, og tømmes ved anonymisering
-- (db.anonymiser_deltaker). Betaler deltakeren selv, kopieres den til paamelding.faktura_* når påmeldingen lages.
CREATE TABLE IF NOT EXISTS deltaker (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epost           CITEXT UNIQUE NOT NULL,
    navn            TEXT NOT NULL,                  -- fullt navn: alltid «fornavn etternavn», settes av db.fullt_navn()
    fornavn         TEXT NOT NULL DEFAULT '',       -- fornavn/etternavn registreres hver for seg (migrering 7)
    etternavn       TEXT NOT NULL DEFAULT '',
    telefon         TEXT,
    arbeidssted     TEXT,
    yrkestittel     TEXT,
    hpr_nr          TEXT,
    visma_kunde_id  TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    adresse         TEXT,                           -- privat adresse (migrering 14), se over tabellen
    postnr          TEXT,
    poststed        TEXT
);

CREATE TABLE IF NOT EXISTS paamelding (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id),
    deltaker_id     BIGINT NOT NULL REFERENCES deltaker(id),
    status          TEXT NOT NULL DEFAULT 'bekreftet' CHECK (status IN ('bekreftet','venteliste','avmeldt')),
    betaler         TEXT NOT NULL DEFAULT 'person' CHECK (betaler IN ('person','organisasjon')),
    betaling        TEXT NOT NULL DEFAULT 'samlet' CHECK (betaling IN ('samlet','per_samling')),
    org_navn        TEXT,
    org_nr          TEXT,
    faktura_epost   TEXT,
    faktura_adresse TEXT,
    faktura_postnr  TEXT,
    faktura_sted    TEXT,
    faktura_ref     TEXT,
    ehf             BIGINT NOT NULL DEFAULT 0,
    rabattkode      TEXT,
    samtykke_ts     TEXT,
    kilde           TEXT NOT NULL DEFAULT 'skjema',
    sveiper_kjort   BIGINT NOT NULL DEFAULT 0,
    sveiper_utsatt  BIGINT NOT NULL DEFAULT 0,
    faktura_onskes_na BIGINT NOT NULL DEFAULT 0,
    faktura_tidligst_dato TEXT,
    faktura_kommentar TEXT,
    intern_kommentar  TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    oppdatert       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    avslatt_ts      TEXT,
    utgatt_ts       TEXT CHECK (utgatt_ts IS NULL OR (status='avmeldt' AND avslatt_ts IS NULL)),
    forlatt_ts      TEXT CHECK (forlatt_ts IS NULL OR (status='avmeldt' AND avslatt_ts IS NULL AND utgatt_ts IS NULL)),
    ekstradeltaker_ts TEXT CHECK (ekstradeltaker_ts IS NULL OR status='bekreftet'),
    UNIQUE (kurs_id, deltaker_id)
);

-- Sensitive opplysninger holdes adskilt og slettes N dager etter kursslutt
CREATE TABLE IF NOT EXISTS sensitivt (
    paamelding_id   BIGINT PRIMARY KEY REFERENCES paamelding(id) ON DELETE CASCADE,
    allergier       TEXT,
    tilrettelegging TEXT
);

-- Samlingsutvalget til ekstradeltakere (migrering 18). En ekstradeltaker (paamelding.ekstradeltaker_ts) deltar enten på HELE kurset
-- (ingen rader her) eller bare på utvalgte samlinger (én rad per samling). Utvalget ryddes når påmeldingen slutter å være
-- ekstradeltaker eller forlater plassen. Slettes en samling, går raden med (CASCADE). Alle samlinger valgt lagres aldri som rader:
-- da er det «hele kurset» (db.sett_ekstradeltaker_samlinger). Ingen persondata: bare to id-er.
CREATE TABLE IF NOT EXISTS ekstradeltaker_samling (
    paamelding_id   BIGINT NOT NULL REFERENCES paamelding(id) ON DELETE CASCADE,
    samling_id      BIGINT NOT NULL REFERENCES samling(id) ON DELETE CASCADE,
    PRIMARY KEY (paamelding_id, samling_id)
);

CREATE TABLE IF NOT EXISTS faktura (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paamelding_id   BIGINT NOT NULL REFERENCES paamelding(id),
    kursdag_id      BIGINT REFERENCES kursdag(id),
    visma_id        TEXT,
    faktura_nr      TEXT,
    belop_nok       BIGINT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'opprettet' CHECK (status IN ('opprettet','sendt','betalt','kreditert','feil')),
    feilmelding     TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

-- Aldri dobbeltfakturering: én samlet faktura, eller én per samling.
CREATE UNIQUE INDEX IF NOT EXISTS faktura_unik ON faktura (paamelding_id, COALESCE(kursdag_id, 0));

-- Forsoket paa aa lage en faktura i Visma (se kommentaren i schema.sql).
CREATE TABLE IF NOT EXISTS faktura_forsok (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paamelding_id   BIGINT NOT NULL REFERENCES paamelding(id),
    kursdag_id      BIGINT REFERENCES kursdag(id),
    status          TEXT NOT NULL CHECK (status IN ('reservert','feilet','ukjent')),
    feilmelding     TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE UNIQUE INDEX IF NOT EXISTS faktura_forsok_unik ON faktura_forsok (paamelding_id, COALESCE(kursdag_id, 0));

CREATE TABLE IF NOT EXISTS oppmote (
    paamelding_id   BIGINT NOT NULL REFERENCES paamelding(id),
    kursdag_id      BIGINT NOT NULL REFERENCES kursdag(id),
    kilde           TEXT NOT NULL CHECK (kilde IN ('qr','kode','zoom','manuell')),
    minutter        BIGINT,
    ts              TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    PRIMARY KEY (paamelding_id, kursdag_id)
);

CREATE TABLE IF NOT EXISTS dokument (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT REFERENCES kurs(id),
    deltaker_id     BIGINT REFERENCES deltaker(id),
    type            TEXT NOT NULL CHECK (type IN ('presentasjon','kontrakt','kursbevis','veiledning','annet')),
    tittel          TEXT NOT NULL,
    url             TEXT NOT NULL,
    publisert       BIGINT NOT NULL DEFAULT 1,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS materiell_krav (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id),
    ansvarlig_navn  TEXT NOT NULL,
    ansvarlig_epost TEXT NOT NULL,
    beskrivelse     TEXT NOT NULL DEFAULT 'Kurspresentasjon',
    frist           TEXT NOT NULL,
    levert_ts       TEXT
);

-- Dedup for ALL utsending (se kommentaren i schema.sql). mottaker er CITEXT: unikheten og oppslagene ignorerer store/
-- smaa bokstaver, akkurat som COLLATE NOCASE i SQLite - ellers kunne samme e-post blitt sendt to ganger.
CREATE TABLE IF NOT EXISTS utsending_logg (
    nokkel          TEXT NOT NULL,
    mottaker        CITEXT NOT NULL,
    type            TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'sendt' CHECK (status IN ('reservert','sendt','feilet','ukjent')),
    sendt_ts        TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    UNIQUE (nokkel, mottaker, type)
);

CREATE TABLE IF NOT EXISTS admin_utsending (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nokkel          TEXT UNIQUE NOT NULL,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id),
    emne            TEXT NOT NULL,
    tekst           TEXT NOT NULL,
    sendt_av_admin_id BIGINT REFERENCES admin_bruker(id),
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    signatur_html   TEXT
);

CREATE TABLE IF NOT EXISTS admin_utsending_mottaker (
    utsending_id    BIGINT NOT NULL REFERENCES admin_utsending(id) ON DELETE CASCADE,
    paamelding_id   BIGINT NOT NULL REFERENCES paamelding(id),
    PRIMARY KEY (utsending_id, paamelding_id)
);

CREATE TABLE IF NOT EXISTS firmapaamelding (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id),
    innsendingsnokkel TEXT UNIQUE NOT NULL,
    kvittering_token  TEXT UNIQUE NOT NULL,
    kontakt_navn    TEXT NOT NULL,                  -- «kontakt_fornavn kontakt_etternavn», satt av db.fullt_navn()
    kontakt_fornavn   TEXT NOT NULL DEFAULT '',
    kontakt_etternavn TEXT NOT NULL DEFAULT '',
    kontakt_epost   TEXT NOT NULL,
    kontakt_telefon TEXT,
    firmanavn       TEXT NOT NULL,
    org_nr          TEXT,
    faktura_ref     TEXT,
    faktura_adresse TEXT,
    faktura_postnr  TEXT,
    faktura_sted    TEXT,
    ehf             BIGINT NOT NULL DEFAULT 0,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS firmapaamelding_rad (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firmapaamelding_id  BIGINT NOT NULL REFERENCES firmapaamelding(id) ON DELETE CASCADE,
    navn                TEXT NOT NULL,
    epost               TEXT NOT NULL,
    paamelding_id       BIGINT REFERENCES paamelding(id),
    feilmelding         TEXT
);

CREATE TABLE IF NOT EXISTS innlogging_token (
    token           TEXT PRIMARY KEY,
    deltaker_id     BIGINT NOT NULL REFERENCES deltaker(id),
    utloper         TEXT NOT NULL,
    brukt           BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS import_forhaandsvisning (
    token           TEXT PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id),
    admin_id        BIGINT NOT NULL REFERENCES admin_bruker(id),
    rader_json      TEXT NOT NULL,
    resultater_json TEXT NOT NULL,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    utloper         TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS hendelse (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts              TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    aktor           TEXT NOT NULL,
    handling        TEXT NOT NULL,
    detaljer        TEXT
);

CREATE TABLE IF NOT EXISTS kunnskap (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kategori        TEXT NOT NULL,
    sporsmal        TEXT NOT NULL,
    svar            TEXT NOT NULL,
    kurs_id         BIGINT REFERENCES kurs(id),
    gyldig_til      TEXT,
    godkjent        BIGINT NOT NULL DEFAULT 0,
    oppdatert       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    oppdatert_av    TEXT
);

CREATE TABLE IF NOT EXISTS henvendelse (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts              TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    deltaker_id     BIGINT REFERENCES deltaker(id),
    epost           TEXT,
    sporsmal        TEXT NOT NULL,
    status          TEXT NOT NULL CHECK (status IN ('besvart','til_adm','lukket')),
    kilder          TEXT,
    grunn           TEXT
);

CREATE TABLE IF NOT EXISTS mal_tekst (
    mal             TEXT NOT NULL,
    felt            TEXT NOT NULL,
    tekst           TEXT NOT NULL,
    oppdatert       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    oppdatert_av    TEXT,
    PRIMARY KEY (mal, felt)
);

CREATE TABLE IF NOT EXISTS teller (
    navn            TEXT PRIMARY KEY,
    verdi           BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS schema_versjon (
    versjon         BIGINT PRIMARY KEY,
    navn            TEXT NOT NULL,
    kjort           TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS kurs_skjemafelt (
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id) ON DELETE CASCADE,
    felt            TEXT NOT NULL,
    synlig          BIGINT CHECK (synlig IS NULL OR synlig IN (0,1)),
    obligatorisk    BIGINT CHECK (obligatorisk IS NULL OR obligatorisk IN (0,1)),
    rekkefolge      BIGINT,
    label           TEXT,
    hjelpetekst     TEXT,
    oppdatert       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    oppdatert_av    TEXT,
    PRIMARY KEY (kurs_id, felt)
);

CREATE TABLE IF NOT EXISTS planlagt_aktivitet (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            TEXT NOT NULL DEFAULT 'plan' CHECK (type IN ('plan','notat')),
    tittel          TEXT NOT NULL,
    fra_dato        TEXT NOT NULL,
    til_dato        TEXT NOT NULL,
    sted            TEXT,
    notat           TEXT,
    opprettet_av    TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    CHECK (til_dato >= fra_dato)
);

-- Perioder i årsplanen: se schema.sql.
CREATE TABLE IF NOT EXISTS kalenderperiode (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            TEXT NOT NULL CHECK (type IN ('skoleferie','sperre','advarsel')),
    navn            TEXT NOT NULL,
    omraade         TEXT,
    fra_dato        TEXT NOT NULL,
    til_dato        TEXT NOT NULL,
    gjelder         TEXT NOT NULL DEFAULT 'alle' CHECK (gjelder IN ('alle','fysisk','online')),
    notat           TEXT,
    opprettet_av    TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    CHECK (til_dato >= fra_dato)
);

CREATE TABLE IF NOT EXISTS dokument_innhold (
    dokument_id     BIGINT PRIMARY KEY REFERENCES dokument(id) ON DELETE CASCADE,
    mimetype        TEXT NOT NULL DEFAULT 'text/html',
    innhold         TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS integrasjon_token (
    navn            TEXT PRIMARY KEY,
    verdi           TEXT NOT NULL,
    oppdatert       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

-- E-posthistorikk: se schema.sql.
CREATE TABLE IF NOT EXISTS sendt_epost (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paamelding_id   BIGINT REFERENCES paamelding(id),
    kurs_id         BIGINT REFERENCES kurs(id),
    nokkel          TEXT NOT NULL,
    type            TEXT NOT NULL,
    mal             TEXT,
    til             TEXT NOT NULL,
    kopi            TEXT,
    fra             TEXT NOT NULL,
    sendt_av        TEXT NOT NULL,
    emne            TEXT NOT NULL,
    html            TEXT NOT NULL,
    status          TEXT NOT NULL CHECK (status IN ('sender','sendt','feilet','ukjent')),
    feilmelding     TEXT,
    opprettet       TEXT NOT NULL,
    sendt_ts        TEXT
);
CREATE INDEX IF NOT EXISTS sendt_epost_paamelding ON sendt_epost (paamelding_id, opprettet);

CREATE TABLE IF NOT EXISTS epost_fil (
    sha256          TEXT PRIMARY KEY,
    mimetype        TEXT NOT NULL,
    storrelse       BIGINT NOT NULL,
    innhold         TEXT NOT NULL,
    opprettet       TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sendt_epost_vedlegg (
    sendt_epost_id  BIGINT NOT NULL REFERENCES sendt_epost(id) ON DELETE CASCADE,
    nr              BIGINT NOT NULL,
    sha256          TEXT NOT NULL REFERENCES epost_fil(sha256),
    filnavn         TEXT NOT NULL,
    innebygd_cid    TEXT,
    PRIMARY KEY (sendt_epost_id, nr)
);

-- Egne felt i påmeldingsskjemaet (migrering 13) og svarene på dem - se schema.sql.
CREATE TABLE IF NOT EXISTS kurs_ekstrafelt (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id) ON DELETE CASCADE,
    type            TEXT NOT NULL,
    label           TEXT NOT NULL,
    hjelpetekst     TEXT,
    valg            TEXT,
    obligatorisk    BIGINT NOT NULL DEFAULT 0 CHECK (obligatorisk IN (0,1)),
    synlig          BIGINT NOT NULL DEFAULT 1 CHECK (synlig IN (0,1)),
    plassering      TEXT NOT NULL DEFAULT 'om_deg',
    rekkefolge      BIGINT NOT NULL DEFAULT 0,
    vis_naar_felt   TEXT,
    vis_naar_verdi  TEXT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    oppdatert       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    oppdatert_av    TEXT,
    CHECK ((vis_naar_felt IS NULL) = (vis_naar_verdi IS NULL))
);

CREATE TABLE IF NOT EXISTS paamelding_svar (
    paamelding_id   BIGINT NOT NULL REFERENCES paamelding(id) ON DELETE CASCADE,
    felt_id         BIGINT NOT NULL REFERENCES kurs_ekstrafelt(id),
    verdi           TEXT NOT NULL,
    PRIMARY KEY (paamelding_id, felt_id)
);

-- Kursside (migrering «kursside»). Speiler schema.sql.
CREATE TABLE IF NOT EXISTS kursside (
    kurs_id             BIGINT PRIMARY KEY REFERENCES kurs(id) ON DELETE CASCADE,
    utkast              TEXT NOT NULL DEFAULT '{}',
    publisert           TEXT,
    versjon             BIGINT NOT NULL DEFAULT 1,
    publisert_versjon   BIGINT,
    aktiv               BIGINT NOT NULL DEFAULT 1 CHECK (aktiv IN (0,1)),
    innsjekk_krever_kode BIGINT NOT NULL DEFAULT 1 CHECK (innsjekk_krever_kode IN (0,1)),
    stenges             TEXT,
    apen_dager          BIGINT CHECK (apen_dager IS NULL OR apen_dager BETWEEN 0 AND 3650),
    endret              TEXT,
    endret_av           TEXT,
    publisert_tid       TEXT,
    publisert_av        TEXT,
    redigerer_av        TEXT,
    redigerer_til       TEXT
);

-- Speiler schema.sql.
CREATE TABLE IF NOT EXISTS kursside_versjon (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id) ON DELETE CASCADE,
    innhold         TEXT NOT NULL,
    arsak           TEXT NOT NULL CHECK (arsak IN ('publisert','sikkerhetskopi')),
    merknad         TEXT,
    versjon         BIGINT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    opprettet_av    TEXT
);
CREATE INDEX IF NOT EXISTS kursside_versjon_kurs ON kursside_versjon (kurs_id, id);

-- Speiler schema.sql.
CREATE TABLE IF NOT EXISTS kursside_fil (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id         BIGINT NOT NULL REFERENCES kurs(id) ON DELETE CASCADE,
    filnavn         TEXT NOT NULL,
    type            TEXT NOT NULL CHECK (type IN ('bilde','dokument')),
    mimetype        TEXT NOT NULL,
    storrelse       BIGINT NOT NULL,
    sha256          TEXT NOT NULL,
    bredde          BIGINT,
    hoyde           BIGINT,
    opprettet       TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    opprettet_av    TEXT,
    UNIQUE (kurs_id, sha256)
);
CREATE INDEX IF NOT EXISTS kursside_fil_kurs ON kursside_fil (kurs_id);

-- Speiler schema.sql.
CREATE TABLE IF NOT EXISTS kursside_fil_innhold (
    fil_id          BIGINT PRIMARY KEY REFERENCES kursside_fil(id) ON DELETE CASCADE,
    innhold         TEXT NOT NULL
);

-- Speiler schema.sql.
CREATE TABLE IF NOT EXISTS min_side_lenke (
    paamelding_id   BIGINT PRIMARY KEY REFERENCES paamelding(id) ON DELETE CASCADE,
    versjon         BIGINT NOT NULL DEFAULT 0,
    stengt          BIGINT NOT NULL DEFAULT 0 CHECK (stengt IN (0,1)),
    endret          TEXT,
    endret_av       TEXT
);
